# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 18:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ), migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=100)),
                ('quantidade_vidas', models.CharField(choices=[
                 (1, 'Uma'), (2, 'Duas'), (3, 'Três'), (4, 'Quatro'), (5, 'Cinco ou mais')], max_length=20)),
                ('pessoa_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='tipo_id', to='Tipo')),
            ],
        ),
    ]
