# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-02 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='pessoa_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Tipo'),
        ),
    ]
